const url = 'https://country-flag.oss-cn-shanghai.aliyuncs.com/'
const suffix = '.webp'

export let list = [
    {
        "code":86,
        "name":"中国大陆",
        "url":url+'cn'+suffix
    },
    {
        "code":852,
        "name":"中國香港",
        "url":url+'hk'+suffix
    },
    {
        "code":853,
        "name":"中國澳門",
        "url":url+'macau'+suffix
    },
    {
        "code":886,
        "name":"中國台灣",
        "url":url+'tw'+suffix
    },
    {
        "code":81,
        "name":"日本国",
        "url":url+'japan'+suffix
    },
    {
        "code":82,
        "name":"한국",
        "url":url+'korea'+suffix
    },
    {
        "code":850,
        "name":"조선",
        "url":url+'north-korea'+suffix
    },
    {
        "code":65,
        "name":"Singapore",
        "url":url+'singapore'+suffix
    },
    {
        "code":60,
        "name":"Malaysia",
        "url":url+'malaysia'+suffix
    },
    {
        "code":84,
        "name":"Việt Nam",
        "url":url+'Vietnam'+suffix
    },
    {
        "code":855,
        "name":"Cambodia",
        "url":url+'Cambodia'+suffix
    },
    {
        "code":856,
        "name":"ປະເທດລາວ",
        "url":url+'Laos'+suffix
    },
    {
        "code":95,
        "name":"မြန်မာ",
        "url":url+'Myanmar'+suffix
    },
    {
        "code":66,
        "name":"ประเทศไทย",
        "url":url+'Thailand'+suffix
    },
    {
        "code":976,
        "name":"Монгол",
        "url":url+'Mongolia'+suffix
    },
    {
        "code":880,
        "name":"বাংলা",
        "url":url+'Bangladesh'+suffix
    },
    {
        "code":63,
        "name":"Philippines",
        "url":url+'Philippines'+suffix
    },
    {
        "code":673,
        "name":"Brunei",
        "url":url+"Brunei.png"
    },

]